### ISSUE TITLE
SPV intergration checklist

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1243]
Here is all the various issues that need to be complete for SPV to be available for usage with decrediton:

- [x] Add "SPV mode" config option
- [x] Remove daemon connectivity while in "SPV mode"
- [x] Remove/replace block count request from insight with another signal from wallet for syncness check
- [x] Remove various functionality that will not be available in "SPV mode"

**Comment by vctt94** [comment]
Can I work on this issue?

**Comment by alexlyp** [comment]
Well let's start discussing various things we need to do here.  The changes in dcrwallet are still a WIP, but we should be able to start completing some of the easier tasks.

**Comment by vctt94** [comment]
Cool, I want to help with dcrwallet checklist as well. I am thinking on start with 

- [ ]  Add "SPV mode" config option
And
- [ ]  Remove various functionality that will not be available in "SPV mode"

How does that sound?

**Comment by alexlyp** [comment]
Yah I think that's a good start
