### ISSUE TITLE
Politeia integration checklist

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1244]
This will depend on completion of #1242 and a future issue concerning proxying remote requests.  This is an important security measure that will be necessary for proper protection of the wallet.

- [x] Request to Politeiawww for proposals to display. 
  We are currently debating whether to display only current votes or all proposals.  I think we could also have a toggle for the user to decide which ones they would like to be shown.  Mostly the concern is information overload.
- [x] Displaying proposals 
  This will depend on a future issue created by @linnutee and Eeter.  I will update this issue with a link to that when it has been added.
- [x] Determine whether the wallet has tickets to cast votes on a particular proposal.  
- [x] Allow user to cast votes for a proposal based on tickets
- [x] Send cast vote hashes to politeiawww 
  Update UX/UI that votes have been cast for a given proposal.

These are a very brief and trimmed down list of tasks that need to be completed.

**Comment by linnutee** [comment]
1st round of drafts as posted to slack: https://xd.adobe.com/view/f2fafab2-0592-408b-9adb-72e1b1493ab3/
